[package]
name = "rs-ts-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
envconfig = "0.10.0"
tokio = "1.38.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
